name: Dispatch
on:
  workflow_dispatch:
    inputs:
      recreate_vm:
        required: false
        type: string
        description: "ad"
        default: "false"

jobs:
  configuration:
    name: Configure job parameters
    runs-on: [ self-hosted ]
    concurrency:
      group: ${{ github.head_ref || github.ref }}-configuration
      cancel-in-progress: true
    outputs:
      is_main_branch: ${{ steps.output.outputs.is_main_branch }}
      version: ${{ steps.output.outputs.version }}
      preview_enable: ${{ steps.output.outputs.preview_enable }}
      preview_infra_provider: ${{ steps.output.outputs.preview_infra_provider }}
      with_github_actions: ${{ steps.output.outputs.with_github_actions }}
      build_no_cache: ${{ steps.output.outputs.build_no_cache }}
      build_no_test: ${{ steps.output.outputs.build_no_test }}
      build_leeway_target: ${{ steps.output.outputs.build_leeway_target }}
      with_large_vm: ${{ steps.output.outputs.with_large_vm }}
      publish_to_npm: ${{ steps.output.outputs.publish_to_npm }}
      publish_to_jbmp: ${{ steps.output.outputs.publish_to_jbmp }}
      with_ws_manager_mk2: ${{ steps.output.outputs.with_ws_manager_mk2 }}
      with_dedicated_emulation: ${{ steps.output.outputs.with_dedicated_emulation }}
      with_ee_license: ${{ steps.output.outputs.with_ee_license }}
      with_slow_database: ${{ steps.output.outputs.with_slow_database }}
      analytics: ${{ steps.output.outputs.analytics }}
      workspace_feature_flags: ${{ steps.output.outputs.workspace_feature_flags }}
    steps:
      - name: "Determine Branch"
        id: branches
        uses: transferwise/sanitize-branch-name@v1
      - name: "Set outputs"
        id: output
        env:
          PR_DESC: '${{ github.event.pull_request.body }}'
        shell: bash
        run: |
          {
            echo "is_main_branch=${{ (github.head_ref || github.ref) == 'refs/heads/main' }}"
            echo "version=${{ steps.branches.outputs.sanitized-branch-name }}-gha.${{github.run_number}}"
            echo "with_github_actions=${{ contains(github.event.pull_request.body, '[x] /werft with-github-actions') }}"
            echo "preview_enable=${{ contains(github.event.pull_request.body, '[x] /werft with-preview') }}"
            echo "preview_infra_provider=${{ contains(github.event.pull_request.body, '[X] /werft with-gce-vm') && 'gce' || 'harvester' }}"
            echo "build_no_cache=${{ contains(github.event.pull_request.body, '[x] leeway-no-cache') }}"
            echo "build_no_test=${{ contains(github.event.pull_request.body, '[x] /werft no-test') }}"
            echo "build_leeway_target=$(echo "$PR_DESC" | sed -n -e 's/^.*leeway-target=//p' | sed 's/\r$//')"
            echo "with_large_vm=${{ contains(github.event.pull_request.body, '[X] /werft with-large-vm') }}"
            echo "publish_to_npm=${{ contains(github.event.pull_request.body, '[X] /werft publish-to-npm') }}"
            echo "publish_to_jbmp=${{ contains(github.event.pull_request.body, '[X] /werft publish-to-jb-marketplace') }}"
            echo "with_ws_manager_mk2=${{ contains(github.event.pull_request.body, '[X] with-ws-manager-mk2') }}"
            echo "with_dedicated_emulation=${{ contains(github.event.pull_request.body, '[X] with-dedicated-emulation') }}"
            echo "with_ee_license=${{ contains(github.event.pull_request.body, '[X] with-ee-license') }}"
            echo "with_slow_database=${{ contains(github.event.pull_request.body, '[X] with-slow-database') }}"
            echo "analytics=${{ contains(github.event.pull_request.body, '[X] analytics') }}"
            echo "workspace_feature_flags=$(echo "$PR_DESC" | grep -oP '(?<=\[X\] workspace-feature-flags).*')"
          } >> $GITHUB_OUTPUT

  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Any Name Bash Test Step
        env:
          PR_DESC: '${{ github.event.pull_request.body || inputs.pr_description }}'
        shell: bash
        run: |
          echo ${{ inputs.recreate_vm }}
          echo ${{ needs.configuration.outputs.is_main_branch }}
          echo ${{ needs.configuration.outputs.version }}
          echo ${{ needs.configuration.outputs.preview_enable }}
          echo ${{ needs.configuration.outputs.preview_infra_provider }}
          echo ${{ needs.configuration.outputs.with_github_actions }}
          echo ${{ needs.configuration.outputs.build_no_cache }}
          echo ${{ needs.configuration.outputs.build_no_test }}
          echo ${{ needs.configuration.outputs.build_leeway_target }}
          echo ${{ needs.configuration.outputs.with_large_vm }}
          echo ${{ needs.configuration.outputs.publish_to_npm }}
          echo ${{ needs.configuration.outputs.publish_to_jbmp }}
          echo ${{ needs.configuration.outputs.with_ws_manager_mk2 }}
          echo ${{ needs.configuration.outputs.with_dedicated_emulation }}
          echo ${{ needs.configuration.outputs.with_ee_license }}
          echo ${{ needs.configuration.outputs.with_slow_database }}
          echo ${{ needs.configuration.outputs.analytics }}
          echo ${{ needs.configuration.outputs.workspace_feature_flags }}
