name: Dev

on:
  workflow_dispatch:
  issue_comment:
    types: [ created ]

jobs:
  dispatch-gh:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/werft run') }}
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.comment-branch.outputs.head_ref }}
    steps:
      - uses: xt0rted/pull-request-comment-branch@v1.4.0
        id: comment-branch
#      - uses: actions/checkout@v3
      - name: Workflow dispatch
        env:
          GH_TOKEN: ${{ github.token }}
#          PR_DESC: '${{ github.event.pull_request.body || github.event.issue.body }}'
        shell: bash
        run: |
          echo ${{ steps.comment-branch.outputs.head_ref }}
          echo ${{ contains(github.event.comment.body, '[x] /werft recreate-vm') }}
          gh workflow run dispatch.yaml --repo vulkoingim/actions-test  -f recreate_vm=${{ contains(github.event.comment.body, '[x] /werft recreate-vm') }} -f pr_number=${{ github.event.issue.number }} --ref ${{ steps.comment-branch.outputs.head_ref }}

#  dispatch:
#    uses: vulkoingim/actions-test/.github/workflows/dispatch.yaml@${{ needs.dispatch-gh.outputs.branch }}
#    with:
#      pr_description: ${{ github.event.pull_request.body || github.event.issue.body }}
