name: Dev

on:
  workflow_dispatch:
  issue_comment:
    types: [ created ]

jobs:
  dispatch-gh:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.comment-branch.outputs.head_ref }}
    steps:
      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
      - uses: actions/checkout@v3
      - name: Workflow dispatch
        env:
          GH_TOKEN: ${{ github.token }}
          PR_DESC: '${{ github.event.pull_request.body || github.event.issue.body }}'
        shell: bash
        run: |
          echo ${{ steps.comment-branch.outputs.head_ref }}
          gh workflow run dispatch.yaml -f pr_description=${{ github.event.pull_request.body || github.event.issue.body }} --ref ${{ steps.comment-branch.outputs.head_ref }}

#  dispatch:
#    uses: vulkoingim/actions-test/.github/workflows/dispatch.yaml@${{ needs.dispatch-gh.outputs.branch }}
#    with:
#      pr_description: ${{ github.event.pull_request.body || github.event.issue.body }}
