name: Wrapper test

on:
  push:
    paths:
      - '.github/workflows/wrapper.yaml'
  workflow_dispatch:
    inputs:
      env:
        description: 'Comma separated list of strings with the env trigger the workflows for'
        required: true
        type: string
        default: '["staging","production"]'
      resources:
        description: 'Comma separated list of strings with the resource trigger the workflows for'
        required: true
        type: string
        default: 'ami,prerequisites'
      run:
        description: ''
        required: true
        type: boolean

jobs:
  push:
    runs-on: ubuntu-latest
    if: ${{ inputs.run }}
    strategy:
      matrix:
        env: ${{fromJson(github.event_name == 'push' && '["staging", "production"]' || inputs.env )}}
    steps:
      - uses: actions/checkout@v3
      - name: Send greeting
        run: |
          git fetch --tags
          git describe --tags --abbrev=0
          git rev-parse HEAD
          echo "${{ matrix.env }}"
          echo "${{ toJSON(github) }}"
          echo "${{ toJSON(github.event) }}"

#  ami:
#    runs-on: ubuntu-latest
#    #    if: contains(github.event.head_commit.modified, '**/ami/**') || github.event_name == 'workflow_dispatch'
#    strategy:
#      matrix:
#        env: ${{fromJson(github.event.inputs.env != '' && github.event.inputs.env || '["staging", "production"]')}}
#    steps:
#      - name: Run job for resource ami
#        run: |
#          echo "${{ matrix.env }}"

#  prerequisites:
#    runs-on: ubuntu-latest
#    if: contains(github.event.head_commit.modified, '**/prerequisites/**') || github.event_name == 'workflow_dispatch'
#    strategy:
#      matrix:
#        env: ${{fromJson(github.event.inputs.env ?? '["staging", "production"]')}}
#    steps:
#      - name: Check out code
#        uses: actions/checkout@v2
#
#      - name: Run job for resource prerequisites
#        run: |
#          # Your commands here for the resource prerequisites
