name: Wrapper test

on:
  push:
  #    branches:
  #      - main
  #    paths:
  #      - "wrapper.yaml"
  workflow_dispatch:
    inputs:
      env:
        description: 'Comma separated list of strings with the env trigger the workflows for'
        required: true
        type: string
        default: "staging,production"
      resources:
        description: 'Comma separated list of strings with the resource trigger the workflows for'
        required: true
        type: string
        default: "ami,prerequisites"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: |
          echo "${{ github.event.inputs.env }}"
          echo "${{ fromJSON('["staging", "production"]') }}"
          echo "${{ toJSON('["staging", "production"]') }}"
          echo "${{ toJSON('["staging", "production"]') }}"
          echo "tojson: ${{ toJSON('[ github.event.inputs.resources ]') }}"
          echo "tojson: ${{ toJSON('[ github.event.inputs.env ]') }}"
          echo "fromjson: ${{ fromJSON('[ github.event.inputs.resources ]') }}"
          echo "fromjson: ${{ fromJSON('[ github.event.inputs.env ]') }}"
          echo "${{ github.event.inputs.resources != '' && github.event.inputs.resources || fromJSON('["staging", "prod"]') }}"
          echo "${{ github.event.inputs }}"
          echo "${{ github.event.inputs.resources }}"
          echo "${{ github.event.inputs.env }}"
